version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5478:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: estudiantesdb
    volumes:
      - ./postgre25765:/var/lib/postgresql/data